[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = [""]
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "insta-scrape>=2.1.2",
    "instaloader>=4.14.1",
    "requests>=2.32.3",
]
